### ISSUE TITLE
Use of `new Buffer` is deprecated (generates warning in Node 10)

### ISSUE THREAD

**Issue by jacobq** [akileez/toolz#31]
Please consider changing [this line of the `peek-stream` code](
https://github.com/akileez/toolz/blob/72e47d038bef9d05a9692df25ecae56b95f6bd90/src/stream/peek-stream.js#L28) to check for `Buffer.from` or `allocUnsafe` and only fall-back to `new Buffer` if a newer method isn't available.

(Maybe this is an [upstream problem](https://github.com/mafintosh/peek-stream)?)

**Comment by akileez** [comment]
i know its been forever but presently in the process of rewriting the entire lib. thanks for issue. just getting back into the swing of coding again.

**Comment by akileez** [comment]
this project has been re-written from scratch. outdated code was problem due to change in node. 
code has not been released to github as of yet.
